### ISSUE TITLE
Cached Spec Writes are Unsupported

### ISSUE THREAD

**Issue by ln-vidrio** [NeurodataWithoutBorders/matnwb#149]
At the current moment, MatNWB does not support writing schema files or cached specs.

The reason for not writing cached specs stems from the fact that cached specs are, by default, only written in JSON format.  This is not possible with MatNWB's YAML parser.

However, should we work around this issue, the default YAML string produced by the YAML parser on export() produces a YAML with specific tags that end up breaking the default pynwb yaml importer, shown below:
```
!java.util.LinkedHashMap
namespaces: 
- !java.util.LinkedHashMap
   name: core
   doc: NWB namespace
...
   full_name: NWB core
   schema: 
   - !java.util.LinkedHashMap
      source: nwb.base.yaml
      title: Base data types
      doc: This source module contains base data types used throughout the NWB:N data format.
   - !java.util.LinkedHashMap
      source: nwb.epoch.yaml
      title: Epochs
      doc: This source module contains neurodata_types for epoch data.
...
   version: 2.0.1
```
