### ISSUE TITLE
Add Data Scaling

### ISSUE THREAD

**Issue by ln-vidrio** [NeurodataWithoutBorders/matnwb#185]
```yaml
datasets:
- name: data
  dims:
  - name: times
    required: true
    length: null
    doc: optional doc string
  - name: electrodes
    required: false
    length: null
    doc: optional doc string
  - name: dim3
    required: false
    length: null
    doc: optional doc string
  coords:
  - name: time
    dims_index: 0
    coord:
    - dataset_name: timestamps
      dims_index: 0
      type: aligned
  - name: electrodes
    dims_index: 1
    coord:
    - dataset_name: electrodes
      dims_index: 0
      type: aligned
  - name: z
    dims_index:
    - 0
    - 1
    coord:
    - dataset_name: arbitrary_2d_mask
      dims_index:
      - 0
      - 1
      type: aligned
```

Note:
All classes that have Datasets with Data Scaling will also embed two attributes:
- coordinates
- dimensions
which are a JSON-encoded array and object respectively.
