### ISSUE TITLE
validshapes in generated classes of extensions depends in dims

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#67]
The `validshapes` value for datasets of generated classes of extensions should depend only on the `shape` attribute of a dataset. A dataset with

```
shape:
    - null
```

should result in `validshapes = {[Inf]};`. This is indeed the case when 

```
dims:
    - something
```

is present, but if there is no `dims` feature in the extension yaml file, the class validator is generated as `validshapes = {[1]};`. This is an error- the "dims" feature is only meant to be used as a form of documentation and should not affect the generated code (aside from perhaps comments within the generated classes).

Here is an example extensions file that illustrates this issue:

works:
```
groups:
- neurodata_type_def: HilbertSeries
  neurodata_type_inc: ElectricalSeries
  doc: output of hilbert transform
  attributes:
  - name: help
    dtype: text
    doc: help
    value: ENTER HELP INFO HERE
  datasets:
  - name: filter_centers
    dtype: float
    doc: in Hz
    shape:
    - null
    dims:
    - frequency
```

doesn't work (for filter_center):
```
groups:
- neurodata_type_def: HilbertSeries
  neurodata_type_inc: ElectricalSeries
  doc: output of hilbert transform
  attributes:
  - name: help
    dtype: text
    doc: help
    value: ENTER HELP INFO HERE
  datasets:
  - name: filter_centers
    dtype: float
    doc: in Hz
    shape:
    - null
```
